
# Apple is stupid so I have to this.

OPTS = -I /opt/homebrew/Cellar/sfml/2.6.0/include -L /opt/homebrew/Cellar/sfml/2.6.0/lib -l sfml-system -l sfml-window -l sfml-graphics -l sfml-audio -l sfml-network

main:
	g++ main.cpp $(OPTS)